# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='LessonDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('body', models.TextField()),
                ('caption', models.CharField(max_length=1000)),
                ('body_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlearning.BodyType')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlearning.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('title', models.CharField(max_length=250)),
                ('objective', models.CharField(max_length=1000)),
                ('sequence', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('objective', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=250)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlearning.Term')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlearning.Topic'),
        ),
    ]
