# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlearning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1000)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='mlearning.Assessment')),
                ('choice_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessmentchoicetype', to='mlearning.BodyType')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1000)),
                ('choice_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choicetype', to='mlearning.BodyType')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='mlearning.Topic'),
        ),
        migrations.AlterField(
            model_name='lessondetail',
            name='body_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodytype', to='mlearning.BodyType'),
        ),
        migrations.AlterField(
            model_name='lessondetail',
            name='caption',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='lessondetail',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessondetails', to='mlearning.Lesson'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='topic',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='mlearning.Term'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questiontype', to='mlearning.QuestionType'),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mlearning.Topic'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='mlearning.Question'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessmenttype', to='mlearning.QuestionType'),
        ),
    ]
