# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlearning', '0005_assessment_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='lesson_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_lesson_detail', to='mlearning.LessonDetail'),
        ),
        migrations.AddField(
            model_name='topic',
            name='video',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
