# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emassage', '0002_course_coverimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('sequence', models.IntegerField(unique=True)),
                ('coverImage', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sequence', models.IntegerField(unique=True)),
                ('coverImage', models.FileField(blank=True, null=True, upload_to='')),
                ('pdf', models.FileField(upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='emassage.Category')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='sequence',
            field=models.IntegerField(unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='emassage.Course'),
        ),
    ]
