# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emassage', '0007_auto_20170114_1325'),
        ('emassage', '0007_auto_20170111_0358'),
    ]

    operations = [
    ]
