# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 00:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emassage', '0008_merge_20170116_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentVote',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('vote', models.IntegerField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_votes', to='emassage.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForumVote',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('vote', models.IntegerField()),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_votes', to='emassage.Forum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_forum_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
