# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emassage', '0009_commentvote_forumvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumvote',
            name='vote',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
