# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 02:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emassage', '0010_auto_20170116_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumvote',
            name='forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_votes', to='emassage.Forum'),
        ),
        migrations.AlterField(
            model_name='forumvote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_forum_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
