# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 02:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emassage', '0011_auto_20170116_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumvote',
            name='forum',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='forum_votes', to='emassage.Forum'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forumvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_forum_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forumvote',
            name='vote',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
