# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-22 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emassage', '0013_videosimulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
