# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emassage', '0016_twistword'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
