# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-05 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emassage', '0018_auto_20170205_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='page',
        ),
        migrations.AddField(
            model_name='question',
            name='page',
            field=models.IntegerField(default=0),
        ),
    ]
