# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emassage', '0019_auto_20170205_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='youtube_code',
        ),
        migrations.RemoveField(
            model_name='question',
            name='page',
        ),
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='lessondetail',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_lessons', to='emassage.Lesson'),
        ),
        migrations.AddField(
            model_name='question',
            name='lesson_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_lesson_detail', to='emassage.LessonDetail'),
            preserve_default=False,
        ),
    ]
