# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emassage', '0020_auto_20170228_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='pdf',
        ),
    ]
